# Generated by Django 5.0 on 2025-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0003_alter_param_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('systems', 'Systems Parameters Integrations'), ('app', 'Application Parameters'), ('sidemenu', 'Side Menu'), ('topmenu', 'Top Menu'), ('prj', 'Project')], default='app', max_length=30)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('option', models.CharField(default='', max_length=1000)),
                ('json', models.TextField(default='', max_length=75000)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
